### ISSUE TITLE
Liczyć średnią, medianę, odchylenie oraz liczność bez odmów odpowiedzi oraz "Nie wiem/Nie dotyczy"

### ISSUE THREAD

**Issue by kiryk** [ankieter-gui/interface#41]
Domyślnie neutralne odpowiedzi powinny być ignorowane w każdej statystyce z wyjątkiem N*.

**Comment by emilekm2142** [comment]
Jest zrobiony tylko GUI. Nie można jeszcze wysłać filtrów ignorujących do backendu.
